<a href="https://colab.research.google.com/github/sahil301290/MachineLearning/blob/main/Gradient_Descent_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Gradient Descent Optimization based USA Housing Prediction

Dataset: https://www.kaggle.com/vedavyasv/usa-housing

Importing Libraries

In [1]:
import numpy as np
import pandas as pd

Importing USA Housing CSV File

In [2]:
df = pd.read_csv("USA_Housing.csv")
df.head(5)

Avg. Area Income  ...                                            Address
0      79545.458574  ...  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1      79248.642455  ...  188 Johnson Views Suite 079\nLake Kathleen, CA...
2      61287.067179  ...  9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3      63345.240046  ...                          USS Barnett\nFPO AP 44820
4      59982.197226  ...                         USNS Raymond\nFPO AE 09386

[5 rows x 7 columns]

Exploratory Data Analysis

In [3]:
X=df.iloc[:,0:5]
X.head()

Avg. Area Income  ...  Area Population
0      79545.458574  ...     23086.800503
1      79248.642455  ...     40173.072174
2      61287.067179  ...     36882.159400
3      63345.240046  ...     34310.242831
4      59982.197226  ...     26354.109472

[5 rows x 5 columns]

In [12]:
y = df.iloc[:,5]
y = np.array(y)
y = y.reshape(-1,1)
#y = pd.DataFrame(y)
y

array([[1059033.55787012],
       [1505890.91484695],
       [1058987.98787608],
       ...,
       [1030729.58315229],
       [1198656.87240769],
       [1298950.48026696]])

In [ ]:
X=df.iloc[:,0:5]
Y=df.iloc[:,5]
print(X)
Y=np.array(Y)
Y=Y.reshape(-1,1)
print(Y)

      Avg. Area Income  ...  Area Population
0          79545.45857  ...      23086.80050
1          79248.64245  ...      40173.07217
2          61287.06718  ...      36882.15940
3          63345.24005  ...      34310.24283
4          59982.19723  ...      26354.10947
...                ...  ...              ...
4995       60567.94414  ...      22837.36103
4996       78491.27543  ...      25616.11549
4997       63390.68689  ...      33266.14549
4998       68001.33124  ...      42625.62016
4999       65510.58180  ...      46501.28380

[5000 rows x 5 columns]
[[1059033.558]
 [1505890.915]
 [1058987.988]
 ...
 [1030729.583]
 [1198656.872]
 [1298950.48 ]]


Standard Normalization

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled= np.insert(X_scaled, 0, values=1, axis=1)

In [14]:
X_scaled

array([[ 1.        ,  1.02865969, -0.29692705,  0.02127433,  0.08806222,
        -1.31759867],
       [ 1.        ,  1.00080775,  0.02590164, -0.25550611, -0.72230146,
         0.40399945],
       [ 1.        , -0.68462916, -0.11230283,  1.5162435 ,  0.93084045,
         0.07240989],
       ...,
       [ 1.        , -0.48723454,  1.28447022, -2.17026949, -1.50025059,
        -0.29193658],
       [ 1.        , -0.05459152, -0.44669439,  0.14154061,  1.18205319,
         0.65111608],
       [ 1.        , -0.28831272,  0.01521477, -0.19434166,  0.07185495,
         1.04162464]])

Train Test Split

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

Calculating Beta Vector

In [16]:
beta=np.zeros(6)
number_of_iterations=1000
learning_rate=0.01
n = 5

In [17]:
for i in range(number_of_iterations):
  x0_gradient=0
  x1_gradient=0
  x2_gradient=0
  x3_gradient=0
  x4_gradient=0
  x5_gradient=0
for j in range(len(X_train)):
  a=X_train[j,0]
  b=X_train[j,1]
  c=X_train[j,2]
  d=X_train[j,3]
  e=X_train[j,4]
  f=y_train[j]

  x0_gradient+=(beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)
  x1_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*a)
  x2_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*b)
  x3_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*c)
  x4_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*d)
  x5_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*e)
  
  beta[0]=beta[0]-learning_rate/n*x0_gradient
  beta[1]=beta[1]-learning_rate/n*x1_gradient
  beta[2]=beta[2]-learning_rate/n*x2_gradient
  beta[3]=beta[3]-learning_rate/n*x3_gradient
  beta[4]=beta[4]-learning_rate/n*x4_gradient
  beta[5]=beta[5]-learning_rate/n*x5_gradient
print(beta)

[-3.81440828e+09 -3.81440828e+09  1.73425386e+10 -2.19472274e+10
  1.81090639e+10 -1.22054823e+10]


Predictions

In [18]:
#X_test=np.insert(X_test,0,values=1,axis=1)
#print(X_test.shape)
beta=np.array(beta).reshape(-1,1)
print(beta.shape)
y_predict=X_test.dot(beta)
print(y_predict.shape)

(6, 1)
(1500, 1)


In [19]:
y_predict

array([[ 8.56833597e+09],
       [-3.73029171e+09],
       [-4.24440430e+09],
       ...,
       [-2.29267672e+10],
       [-1.64960643e+10],
       [-3.27646123e+10]])

Metric-based evaluations

In [20]:
error=y_test-y_predict
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
mean_square_error=sum_square_error/len(y_predict)
print(mean_square_error)

9.88102376986474e+20


In [21]:
rms_error=np.sqrt(mean_square_error)
print(rms_error)

31434095771.732864


In [22]:
y_mean=np.mean(y_test)
total_variance=np.sum((y_test-y_mean)**2)
r_square = (1-sum_square_error/total_variance)
print(rms_error)

31434095771.732864


In [23]:
N = len(y_predict) #N is the total sample size
k = 5              #k is the number of predictors
adj_r_sq = 1-(((1-r_square)*(N-1))/(N-k-1))
print(adj_r_sq)

-8401038521.630934
